<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>parent_pom</artifactId>
        <groupId>io.github.javifalces</groupId>
        <version>1.0.11-SNAPSHOT</version>
        <relativePath>../../parent_pom/pom.xml</relativePath>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <name>${project.groupId}:${project.artifactId}</name>
    <description>Broker instances for HFTFramework</description>
    <url>https://github.com/javifalces/HFTFramework</url>

    <artifactId>broker_connector_instances</artifactId>
    <properties>
        <com.squareup.retrofit2.version>2.5.0</com.squareup.retrofit2.version>
        <xchange.version>5.2.5</xchange.version>
    </properties>


    <dependencies>
        <dependency>
            <groupId>io.github.javifalces</groupId>
            <artifactId>models</artifactId>
        </dependency>

        <!--Metatrader zeromq-->
        <dependency>
            <groupId>io.github.javifalces</groupId>
            <artifactId>connectors</artifactId>
        </dependency>


        <!--binance api -->
        <dependency>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>retrofit</artifactId>
            <version>${com.squareup.retrofit2.version}</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>converter-jackson</artifactId>
            <version>${com.squareup.retrofit2.version}</version>
        </dependency>


        <!--        XChange-->
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-core</artifactId>
            <version>${xchange.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-core</artifactId>
            <version>${xchange.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>


        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-service-netty</artifactId>
            <version>${xchange.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!--        coinbase-->
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-coinbasepro</artifactId>
            <version>${xchange.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-coinbasepro</artifactId>
            <version>${xchange.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!--        kraken-->
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-kraken</artifactId>
            <version>${xchange.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-kraken</artifactId>
            <version>${xchange.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!--        bitmex-->
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-bitmex</artifactId>
            <version>${xchange.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-bitmex</artifactId>
            <version>${xchange.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!--        binance-->
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-binance</artifactId>
            <version>${xchange.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!--        bybit-->
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-bybit</artifactId>
            <version>${xchange.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-bybit</artifactId>
            <version>${xchange.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-binance</artifactId>
            <version>${xchange.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!--required at runtime by xchange-stream-binance's Ed25519 WebSocket API user-data-stream
        authentication (BinanceUserDataSpotStreamingService); not declared as a transitive dep-->
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
            <version>1.78.1</version>
        </dependency>

        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.10</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>


    </dependencies>

    <build>
        <plugins>
            <!--Adding to create package function-->
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
            </plugin>
        </plugins>
    </build>


</project>