class CandleType:
    time_1_min = "time_1_min"
    mid_time_seconds_threshold = "mid_time_seconds_threshold"
    time_5_min = "time_5_min"
    time_30_min = "time_30_min"
    time_1_hour = "time_1_hour"
    time_1_day = "time_1_day"
    volume_threshold_depth = "volume_threshold_depth"
    volume_1_lot = "volume_1_lot"
    volume_10_lot = "volume_10_lot"
    volume_100_lot = "volume_100_lot"
    dollar_1 = "dollar_1"
    dollar_10 = "dollar_10"
