<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>parent_pom</artifactId>
        <groupId>io.github.javifalces</groupId>
        <version>1.0.11-SNAPSHOT</version>
        <relativePath>../parent_pom/pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <name>${project.groupId}:${project.artifactId}</name>
    <description>Executables for HFTFramework</description>
    <url>https://github.com/javifalces/HFTFramework</url>

    <artifactId>executables</artifactId>
    <packaging>pom</packaging>


    <modules>
        <module>Backtest</module>
        <module>MetatraderEngine</module>
        <module>AlgoTradingZeroMq</module>
        <module>XChangeEngine</module>
        <module>InteractiveBrokersEngine</module>
        <module>PrivateTradingExecutables</module>

    </modules>




</project>