<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>parent_pom</artifactId>
        <groupId>io.github.javifalces</groupId>
        <version>1.0.11-SNAPSHOT</version>
        <relativePath>../parent_pom/pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <name>${project.groupId}:${project.artifactId}</name>
    <description>TradingAlgorithms for HFTFramework</description>
    <url>https://github.com/javifalces/HFTFramework</url>

    <artifactId>trading_algorithms</artifactId>
    <dependencies>

        <dependency>
            <groupId>io.github.javifalces</groupId>
            <artifactId>algorithmic_trading_framework</artifactId>
        </dependency>

        <dependency>
            <groupId>org.msgpack</groupId>
            <artifactId>msgpack-core</artifactId>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>